# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Python 3.12 image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy requirements and source
COPY requirements.txt .
COPY jira_reporter_server.py .
COPY pyproject.toml .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port (if needed by SSE, but stdio uses no HTTP)
# EXPOSE 8000

# Default command
CMD ["python", "jira_reporter_server.py"]
